<a href="https://colab.research.google.com/github/BrittGeek/ANN_Hydrology/blob/master/Import_CSV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
from google.colab import files
up = files.upload()

Saving CV_FINAL_GIS2.csv to CV_FINAL_GIS2 (1).csv

In [13]:
import io
import pandas as pd
import rasterio 
df2 = pd.read_csv(io.BytesIO(up['CV_FINAL_GIS2.csv']))

ModuleNotFoundError: ignored

In [12]:
df2.head()

          LON        LAT  NoNAN  ...  10/15/2016  11/15/2016  12/15/2016
0 -122.396944  40.366944      4  ...         NaN         NaN         NaN
1 -122.350000  39.766667      1  ...         NaN         NaN         NaN
2 -122.291389  40.345278      5  ...         NaN         NaN         NaN
3 -122.192778  39.423333      1  ...         NaN         NaN         NaN
4 -122.174444  40.183056      4  ...         NaN         NaN         NaN

[5 rows x 176 columns]